# Generated by Django 5.2.5 on 2025-10-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_description',
            new_name='recipeDescription',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_image',
            new_name='recipeImage',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_name',
            new_name='recipeName',
        ),
    ]
