# Generated by Django 5.2.5 on 2025-10-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_recipe_description_recipe_recipedescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipeImage',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/images/'),
        ),
    ]
