# Generated by Django 5.2.5 on 2025-11-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_recipeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipeImage',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
